name: delete tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: image tag to delete
        required: true

jobs:
  purge-image:
    name: Delete image from ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.0.0
        with:
          # NOTE: at now only orgs is supported
          owner: tomhuang12
          name: podinfo
          token: ${{ secrets.GHCR_TOKEN }}
          tag: ${{ github.event.inputs.tag }}