name: deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: image tag to push
        required: true
      client:
        description: client name used in tagging
        required: true

jobs:
  deploy-dv:
    runs-on: ubuntu-latest
    environment: 'dv'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: deploy
      uses: ./.github/actions/retag
      with:
        GHCR_USERNAME: tomhuang12
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        tag: ${{ github.event.inputs.tag }}
        client: ${{ github.event.inputs.client }}
        env: dv

  deploy-sg:
    runs-on: ubuntu-latest
    environment: 'sg'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: deploy
      uses: ./.github/actions/retag
      with:
        GHCR_USERNAME: tomhuang12
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        tag: ${{ github.event.inputs.tag }}
        client: ${{ github.event.inputs.client }}
        env: sg

  deploy-pd:
    runs-on: ubuntu-latest
    environment: 'pd'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: deploy
      uses: ./.github/actions/retag
      with:
        GHCR_USERNAME: tomhuang12
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        tag: ${{ github.event.inputs.tag }}
        client: ${{ github.event.inputs.client }}
        env: pd